### ISSUE TITLE
Plugin 2.4 Teamcity 9.1.7 : Incompatible runner: Allure Report

### ISSUE THREAD

**Issue by anuvratashu** [allure-framework/allure-teamcity#42] opened 2016-06-14 11:54 UTC
I have TC 9.1.7 and Java 1.7. However, the error is still comming up
Incompatible runner: Allure Report
not sure how to add the allure reporting to the Teamcity.

if i remove the Allure Report then the build runs fine.

![image](https://cloud.githubusercontent.com/assets/14295329/16041764/e350c308-3254-11e6-8e0b-8ef496532231.png)

**Comment by ViaMay** [comment] 2016-07-18 14:40
don't work too!
I have TC 9.1.7 and Java 1.8.

**Comment by valmaev** [comment] 2016-07-28 09:45
I encountered same issue with TeamCity 10.0:

- I uploaded ``allure-commandline.zip`` in ``Administration -> Integrations -> Tools`` section.
- After that TeamCity copied this archive to all build-agents but to invalid directory:
  - instead of ``buildagent/tools/allure-commandline``
  - it copies to ``buildagent/tools/generic.allure-commandline``

For each subfolder in ``tools`` TeamCity will create configuration parameter on each build agent with following name: ``teamcity.tool.subfolder``.

Allure TeamCity plugin uses ``teamcity.tool.allure-commandline`` parameter to determine compatible runners but since subfolder name is invalid it shows incompatible runner error.

I'm not sure who should fix this behavior (Allure or TeamCity) but you can apply one of the following **quick fixex**:

1. on each build agent rename folder ``buildagent/tools/generic.allure-commandline`` to ``buildagent/tools/allure-commandline`` and restart them or

1. on each build agent in [buildagent.properties](https://confluence.jetbrains.com/display/TCD10/Build+Agent+Configuration) file add ``teamcity.tool.allure-commandline=<absolute path to allure-commandline>``
   - for example: ``teamcity.tool.allure-commandline=`/opt/buildagent/tools/generic.allure-commandline`

**Comment by baev** [comment] 2016-07-28 11:37
Hi! Sorry for the delay. I'll take a look

**Comment by ViaMay** [comment] 2016-07-28 12:55
I did step 2, and dont have problem. Thank

**Comment by baev** [comment] 2016-07-28 14:34
I can confirm that since TC10 uploaded tools have name with `generic.`prefix. 

>> You can also upload your own tool as a .zip archive: the structure of the tool plugin is described on the Plugins Packaging page. TeamCity will use the name of the zip file as the tool name on all agents. The zip file will be automatically unpacked on the agents to the directory with the same name. [Docs](https://confluence.jetbrains.com/display/TCD10/Installing+Agent+Tools)

@nskvortsov @ekoshkin Hi! Is this works like expected? How am I supposed to deal with this?

**Comment by ekoshkin** [comment] 2016-07-28 15:11
@baev it is a regression in TeamCity 10, I've created an issue for it https://youtrack.jetbrains.com/issue/TW-46452

**Comment by baev** [comment] 2016-07-28 15:15
Thanks

**Comment by arjaysalvadora** [comment] 2016-08-03 11:00
@valmaev quick fixes does not worked in my end. may i know the allure-teamcity-plugin and allure-commandline you used?

**Comment by baev** [comment] 2016-08-03 14:06
@anuvratashu it doesn't matter which version of Allure you are using. Make sure you have an agent with `allure-commandline` tool installed (Agents -> Select agent -> Agent Parameters -> Configuration Parameters contains `teamcity.tool.allure-commandline` parameter with the right path to Allure commandline)

**Comment by valmaev** [comment] 2016-08-11 08:12
[TeamCity 10.0.1](https://blog.jetbrains.com/teamcity/2016/08/teamcity-10-0-1-update/) released and [TW-46452](https://youtrack.jetbrains.com/issue/TW-46452) should be fixed.

**Closed** 2017-07-18 13:52 UTC
